### ISSUE TITLE
checkDHCP hang on connection loss

### ISSUE THREAD

**Issue by fynixtech** [adafruit/Adafruit_CC3000_Library#100]
I am currently using the CC3000 in a project I am working on and I created a function to restart the wifi connection if it is lost. The function is shown below. When I disconnect the router and reconnect it, the CC3000 loses connection and the function executes and reconnects just fine. After reconnecting, if I unplug the router again and plug it back in, the function executes but the CC3000 gets stuck in the checkDHCP part of the code and loops forever. Is there something I am doing wrong or is this an issue? I want to enable the system to be able to reconnect to the access point if the connection is lost and restored. Thanks.

```
void restartWifi(){
  while(cc3000.getStatus()!=STATUS_CONNECTED){
    LED(YELLOW);
    Serial.println(F("Disconnected from "));
    Serial.print(F(WLAN_SSID));
    Serial.println(F(" network!"));
    Serial.println(F(""));
    Serial.println(F(""));
    Serial.print(F("Attempting to reconnect to "));
    Serial.print(F(WLAN_SSID));
    Serial.println(F(" ..."));

    if (!cc3000.begin())  {
      while(1);
      Serial.println(F("BEGIN"));
    }
    if (!cc3000.connectToAP(WLAN_SSID, WLAN_PASS, WLAN_SECURITY)) {
      while(1);
      Serial.println(F("connectToAP"));
    }
    while (!cc3000.checkDHCP()){
      delay(100);
      Serial.println(F("checkDHCP"));
    }
    Serial.println();

    // Print CC3000 IP address. Enable if mDNS doesn't work
    while (!displayConnectionDetails()) {
      delay(500);
      Serial.println(F("displayConnectionDetails"));
    }

  if (!mdns.begin("mechcet", cc3000)) {
    Serial.println(F("Error setting up MDNS responder!"));
    while(1);     
  }
    Serial.println(F("Listening for connections..."));
    LED(GREEN);
  }
}
```

**Comment by vicatcu** [comment]
@fynixtech did you literally just take out

    if (!cc3000.begin())  {
      while(1);
      Serial.println(F("BEGIN"));
    }

and replace it with...

    cc3000.reboot()

... and it worked?

**Comment by fynixtech** [comment]
@vicatcu yes that is what I did. I ended up giving up on the CC3000 because it was way too buggy.

...
void restartWifi() {
  while (cc3000.getStatus() != STATUS_CONNECTED) {
    LED(YELLOW);
    Serial.println(F(""));
    Serial.print(F("Disconnected from "));
    Serial.print(F(WLAN_SSID));
    Serial.println(F(" network!"));
    Serial.println(F(""));
    Serial.print(F("Attempting to reconnect to "));
    Serial.print(F(WLAN_SSID));
    Serial.println(F(" ..."));

    cc3000.reboot();

    if (!cc3000.connectToAP(WLAN_SSID, WLAN_PASS, WLAN_SECURITY)) {
      while (1);
    }
    while (!cc3000.checkDHCP()) {
      delay(100);
    }
    Serial.println();

    // Print CC3000 IP address. Enable if mDNS doesn't work
    while (!displayConnectionDetails()) {
      delay(500);
    }

    if (!mdns.begin("arduino", cc3000)) {
      Serial.println(F("Error setting up MDNS responder!"));
      while (1);
    }
    restServer.begin();
    Serial.println(F("Listening for connections..."));
    LED(GREEN);
  }
}
...

**Comment by steviesama** [comment]
I'm having an issue where it'll stop reading in the middle of reading an http response, and the end of the response looks like garbage. If I let the code I originally wrote run normally using client.available() to wait for a response it can hang, so if I don't get an HTTP 200 response in the first line, or if it waits for input more than 15 iterations, and normally it takes only 1, I just reboot the cc3000, and re-establish everything.

So far it hasn't locked up again, but after that first hiccup where it has to reconnect, it seems like it hits that hiccup regularly after that. Only a clean restart will clear that up. It can sometimes run for hours, up to 9 so far, before it hits the problem.

Does any of that sound familiar? This is my first experience with it.

**Comment by oguzhangedik** [comment]
as summary
//-------------------------------------------------------------------------
boolean isRunRebootMethod = false;

while(true) {
   if(isRunRebootMethod == false) {
       if ( !cc3000.begin() ) {
           Serial.println(F("Couldn't begin()! Check your wiring?"));
           while(1);
       }
   isRunRebootMethod = true;
   }
   else if(isRunRebootMethod == true) {
       cc3000.reboot();
       Serial.println("Reboot method was ran!");
   }
   ...
}
//-------------------------------------------------------------------------
