### ISSUE TITLE
Calling server close has to be based on a timing assumption

### ISSUE THREAD

**Issue by vicatcu** [adafruit/Adafruit_CC3000_Library#121]
In reference to the following lines of code: 

https://github.com/adafruit/Adafruit_CC3000_Library/blob/master/examples/HTTPServer/HTTPServer.ino#L206-L212

I inquired into it on the TI E2E forum here: http://e2e.ti.com/support/wireless_connectivity/f/851/p/394077/1392676#1392676

Which pointed me to here: http://processors.wiki.ti.com/index.php/TX_Complete_Feature

Seems like it might be a plausible alternative to the approach used in the example. I'm not sure what, if any, mods would be needed in the library to make use of that feature, but it seems like it would be a lot better than the "wait a bit then disconnect" strategy that the example encourages. Might also make existing Ethernet server code work more reliably if the behavior were integrated into the library?

**Comment by tdicola** [comment]
Yeah this is a great point and something I had seen earlier too in this long investigation: https://github.com/adafruit/Adafruit_CC3000_Library/issues/51  Let's keep this around as an issue to look at adding.  I think perhaps just having the low level write calls check the TX status before sending more data and busy wait in a loop until it's ready to transmit might be one good option.  However we probably want a timeout to cap how long we wait, just in case there's an issue and we never get the TX ready response.
