### ISSUE TITLE
Unsolicited ARP Request Handling

### ISSUE THREAD

**Issue by vicatcu** [adafruit/Adafruit_CC3000_Library#122]
Recently support for TI CC300 Firmware SDK 1.32 was incorporated into Adafruit_CC3000_Library. @tdicola was anything done to address / expose the updated section of Host Programming guide found here: 

http://processors.wiki.ti.com/index.php/CC3000_Host_Programming_Guide#Unsolicited_ARP_events

**Comment by tdicola** [comment]
Oh great point, yeah I only plumbed the new event into the core code from TI and not into the Adafruit wrapper.  Let's keep this issue around as a note to add it when there's time.  Perhaps just a flag or something similar that someone can read to see the unsolicited ARP status.
