### ISSUE TITLE
how to set static ip address

### ISSUE THREAD

**Issue by tomifarkas** [adafruit/Adafruit_CC3000_Library#123]
It is possible to use the cc3000 shield with static ip address?

**Comment by tdicola** [comment]
Yep, check out the buildtest example and a few commented lines in its setup function:
````
  /* Optional: Set a static IP address instead of using DHCP.
     Note that the setStaticIPAddress function will save its state
     in the CC3000's internal non-volatile memory and the details
     will be used the next time the CC3000 connects to a network.
     This means you only need to call the function once and the
     CC3000 will remember the connection details.  To switch back
     to using DHCP, call the setDHCP() function (again only needs
     to be called once).
  */
  uint32_t ipAddress = cc3000.IP2U32(192, 168, 1, 19);
  uint32_t netMask = cc3000.IP2U32(255, 255, 255, 0);
  uint32_t defaultGateway = cc3000.IP2U32(192, 168, 1, 1);
  uint32_t dns = cc3000.IP2U32(8, 8, 4, 4);
  if (!cc3000.setStaticIPAddress(ipAddress, netMask, defaultGateway, dns)) {
    Serial.println(F("Failed to set static IP!"));
    while(1);
  }
````

Uncomment those lines and set them up for your network, then run the sketch.  The CC3000 will remember the static IP address settings in its non-volatile storage so you can run the other examples afterwards and they should use the same static IP address.

If you want to revert back to using DHCP, check out the commented lines below those in buildtest and you'll see the enable DHCP function.  Uncomment and run that once to switch it back to DHCP for getting an IP address.

**Comment by danyfu** [comment]
That means it the cc3000, will keep it that static ip forover?
