### ISSUE TITLE
availble call has a hidden timeout

### ISSUE THREAD

**Issue by Makuna** [adafruit/Adafruit_CC3000_Library#124]
There is a hidden 5ms timeout in the available call.  While many users will never care, I am using this within a non-preemptive tasking system and this timeout is too long.

I have modified my local copy to use just 1us as the tasking system already keeps this call occurrence to 1 ms and I will be testing this.  I don't know if the lower levels will be effected by the short duration or not.

If this timeout was instead exposed through the available call with the default set to 5ms it would be more useful.  

I could provide a the changes if requested.

**Comment by tdicola** [comment]
No problem, exposing the timeout as an optional parameter sounds like a great idea.  Feel free to send a pull for it, thanks!
