### ISSUE TITLE
fastprint hang (buildtest fails to ping)

### ISSUE THREAD

**Issue by petertorelli** [adafruit/Adafruit_CC3000_Library#130]
I've been using this shield for a while on a R0 UNO. Recently switched to a R3 and it stopped working. I upgraded the firmware to 1.14 and upgraded the IDE to 1.6.0 (Java 7). Buildtest makes it all the way to the ping, but fails to ping adafruit. When I build the WebClient, it makes it all the way to resolving the adafruit hostname IP, but then it hangs after the first `.fasprint(F("\n\n")`. It eventually times-out w/o a failure, prints the line of dashes, and then hangs. I'm powering it externally with enough amperage. 

Seen this before? Any clues where to start?

**Comment by tdicola** [comment]
Can you try flashing the firmware again with the 1.0.6 IDE and running buildtest?  Can grab the binary here: http://arduino.cc/en/Main/OldSoftwareReleases  We've seen a few issues like intermittent lockups with the later IDE and its updated avr-gcc toolchain.  Let's check if what you're hitting is something similar.

**Comment by petertorelli** [comment]
Yep. Works fine with 1.0.6. Since `fastrprint` pretty much calls .send() should I do some diff'ing of the source tree for the TCP lib stuff, or do you have an idea where the problem might be (as you mentioned build chain)?

**Comment by dzzie** [comment]
Were you sending any long strings to fastrprint in a single call?

**Comment by dzzie** [comment]
I was having intermittant problems which finally turned into readily producable last night when I was tweaking some code. I was building a long GET query string and sending a ~150 byte buffer all at once in a single www.fastrprint(char*) call. It was never returning.

I switching to sending the string in chunks as I built it up with sprintf instead and it instantly started working again. Buffer size was now around 50 bytes. (Both on a Uno with a shield and a mega with a breakout).

I Dug a little more, not to the bottom, but to a likely candidate.. search for 
CC3000_MINIMAL_TX_SIZE  in cc3000_common.h and read the notes around it. 

looking below send
--------------------------------------------------
socket.cpp - send -> simple_link_send

	// Copy the data received from user into the TX Buffer
	ARRAY_TO_STREAM(pDataPtr, ((unsigned char *)buf), len);

 #define ARRAY_TO_STREAM(p, a, l) 	{register short _i; for (_i = 0; _i < l; _i++) *(p)++ = ((uint8_t *) a)[_i];}

Also there is this:
--------------------------------------------------
//TX and RX buffer sizes, allow to receive and transmit maximum data at length 8.
#ifdef CC3000_TINY_DRIVER
#define TINY_CC3000_MAXIMAL_RX_SIZE 44
#define TINY_CC3000_MAXIMAL_TX_SIZE 59
#endif

I dont see CC3000_TINY_DRIVER defined anywhere in my code or the library (grep) but the behavior going away when I am below the 59 char limit is suspicious. 


I may add a if(strlen(data) > xx ) serial.println "WARNING: Data Length > blah blah" to my lib
