### ISSUE TITLE
compiling issue in Eclipse CDT

### ISSUE THREAD

**Issue by libiao9096** [adafruit/Adafruit_CC3000_Library#140]
Hello all,
I'm trying to develop CC3000 module based on this CC3000 library created by Adafruit cool guys in Eclipse CDT. For me to undertand more about the code itself, navagation system in Eclipse is very helpful. After I import the code and library, the compiling process returns result as such:

Description	Resource	Path	Location	Type
make: *** [CC3000.elf] Error 1	CC3000		 	C/C++ Problem

Description	Resource	Path	Location	Type
undefined reference to `Adafruit_CC3000::Adafruit_CC3000(unsigned char, unsigned char, unsigned char, unsigned char)'	buildtest.ino	/CC3000	line 44	C/C++ Problem

......and so on basically 24 errors shown undefined reference to 'Adafruit_CC3000'

Can anyone please kindly help me out here?

**Comment by tdicola** [comment]
Hrm I haven't used eclipse CDT unfortunately so I can't offer much help, but in general for undefined references check if you're hitting a problem in compiling or linking.  If it's an undefined reference during the compile then something isn't picking up the header that it expects to see to define a function, so double check it has all the .h files and right paths set.  If it's an error after compiling but during the linking then make sure eclipse knows to include all the right object files it built.  Good luck!
