### ISSUE TITLE
fastrprint sometimes returns negative values

### ISSUE THREAD

**Issue by ClemRz** [adafruit/Adafruit_CC3000_Library#143]
Hi, I'm using an Arduino Uno and when I run this code it sometimes passes and sometimes the fastrprint method returns negative values and take a long time to be executed (whatever the value of _delay is). Does someone know why?
Thanks for your help.

```C++
const char
  _host[] =                   "my.host.com";
const char PROGMEM
  _endPoint[] =               "/input",
  _publicKey[] =              "my_public_key",
  _privateKey[] =             "my_private_key";

...

String data = "field1=value1&field2=value2";
int len = data.length();
  char _data[len+1];
  data.toCharArray(_data, len+1);

...

  handle(client.fastrprint(F("POST "))); handle(client.fastrprint(F2(_endPoint))); handle(client.fastrprint(F("/"))); handle(client.fastrprint(F2(_publicKey))); handle(client.fastrprint(F("?private_key="))); handle(client.fastrprint(F2(_privateKey))); handle(client.fastrprintln(F(" HTTP/1.1")));
  handle(client.fastrprint(F("Host: "))); handle(client.fastrprintln(_host));
  handle(client.fastrprintln(F("Connection: close")));
  handle(client.fastrprintln(F("Content-Type: application/x-www-form-urlencoded;charset=UTF-8")));
  handle(client.fastrprint(F("Content-Length: "))); handle(client.print(len)); handle(client.println());
  handle(client.println());
  handle(client.fastrprintln(_data));
  handle(client.println());

...

void handle(int packets) {
  int _delay = 200;
  Serial.println(packets);
  delay(_delay);
}

```

**Comment by tdicola** [comment]
Ah you're probably hitting an error when the send call that's made by fastrprint fails and returns -1.  You can see more about it from the CC3000 API docs here: http://software-dl.ti.com/ecs/simplelink/cc3000/public/doxygen_API/v1.14/html/group__socket__api.html#ga760cbb2052e03468e15d5a0e267b2545  Unfortunately they don't really have more details on what specific errors might be occuring and just return a -1.  However you might check the server hasn't prematurely closed the connection, you're still connected to the network, etc.
