### ISSUE TITLE
Client objects are not marked as disconnected when disassociated

### ISSUE THREAD

**Issue by matthijskooijman** [adafruit/Adafruit_CC3000_Library#146]
AFAICS from reading the code, when the wifi module becomes disassociated, any open sockets are not marked as disconnected. Testing shows that, when for example the access point is powered off, [a disconnect even is received](https://github.com/adafruit/Adafruit_CC3000_Library/blob/master/Adafruit_CC3000.cpp#L992-L995), but not the [socket close event](https://github.com/adafruit/Adafruit_CC3000_Library/blob/master/Adafruit_CC3000.cpp#L1014-L1020). This means that even though the wifi connection is down, the Client object still reports itself as connected, which I think shouldn't really be happening.

I'm not sure if there is some way to let the CC3000 module produce these socket close events, otherwise it might be good to handle the disconnect even by setting all elements of `closed_sockets` to true?

**Comment by tdicola** [comment]
Ah that's a great point, thanks for raising it.  I don't think we have much control over the CC3k module sending out close events, but explicitly closing them on disconnect sounds like a good idea.  Will keep this issue open with the suggestion until there's time test it and check it works.  Thanks!
