### ISSUE TITLE
Adafruit_CC3000_Client disconnects after a few minutes

### ISSUE THREAD

**Issue by TerenceAnton** [adafruit/Adafruit_CC3000_Library#147]
Hello!

I would like to kindly ask if it is normal operation for Adafruit_CC3000_Client to disconnect after a few minutes of checking `client.connected`. Here is the following code snippet on loop():

`if(client.connected()) {`
`Serial.println("client connected");`
 `} else {`
`Serial.println("client disconnected");`
`}`

I was able to do all the necessary code initialization, etc. in setup().
The firmware version is `Firmware V. : 1.28`

If ever this is a normal operation, is there a way for me to have a re-connection?

**Comment by tdicola** [comment]
Yep the CC3000 does have an idle timeout of 1 minute IIRC.  That is, if there's no data sent or received then after a minute it will close an open connection.  You can change this though and even remove the timeout by calling a configuration function mentioned here: https://e2e.ti.com/support/wireless_connectivity/f/851/t/195398  Specifically add this to your setup after you've initialized the CC3000 library:
````
// Set the CC3000 inactivity timeout to 0 (never timeout).  This will ensure 
// the CC3000 does not close the listening socket when it's idle for more than 
// 60 seconds (the default timeout).  See more information from:
// http://e2e.ti.com/support/low_power_rf/f/851/t/292664.aspx
unsigned long aucDHCP       = 14400;
unsigned long aucARP        = 3600;
unsigned long aucKeepalive  = 30;
unsigned long aucInactivity = 0;
netapp_timeout_values(&aucDHCP, &aucARP, &aucKeepalive, &aucInactivity);
````
You'll also want to add a `#include "utility/netapp.h"` to the top of your sketch too.
