### ISSUE TITLE
Release 1.0.1/1.0.2 contain version 1.0.0 in library.properties

### ISSUE THREAD

**Issue by matthijskooijman** [adafruit/Adafruit_CC3000_Library#149]
Per subject - it seems that the latest two releases forgot to update library.properties. Because of this, the Arduino library manager has only picked up the 1.0.0 released, rejecting the newer two tags, since they contain a version that is already  known (the library manager only looks at library.properties, it ignores the name of the tag).

To fix, I think a new 1.0.3 version should be released, with no changes other than fixing library.properties. Fixing the 1.0.2 tag is also an option, but just bumping the version will likely prevent confusion later.

**Comment by tdicola** [comment]
Ah thanks for catching the issue--just bumped up to 1.0.3 in the library.properties and tagged a new release.  This should get picked up by Arduino's library manager in a few hours.  Thanks!
