### ISSUE TITLE
Use vendor zone for pool.ntp.org 

### ISSUE THREAD

**Issue by gfk** [adafruit/Adafruit_CC3000_Library#155]
I see that you're using pool.ntp.org in the InternetTime.ino example. This is not the recommended practice.

To allow you to use the pool as the default time service in your application, we will set you up with special hostnames, for example 0.vendor.pool.ntp.org, 1.vendor.pool.ntp.org, 2.vendor.pool.ntp.org and 3.vendor.pool.ntp.org.

You must absolutely not use the default pool.ntp.org zone names as the default configuration in your application or appliance.

Check this page for more infos: http://www.pool.ntp.org/vendors.html [^]

Thanks and let me know if you need more infos.

**Comment by ladyada** [comment]
done!
