### ISSUE TITLE
freegeoip.net doesn't exist any more

### ISSUE THREAD

**Issue by fede2cr** [adafruit/Adafruit_CC3000_Library#158]
GeoLocation.ino makes reference to a domain that is on a parked domain. It could be used by an attacker who reactivates the domain to send back bogus replies.

I tried to look for another free way to do it for a pyportal patch for circuitpython but can't find any.

I guess the safest thing would be to remove the reference to the domain in the code.

**Comment by siddacious** [comment]
@dherrada please clean this up 🧹

**Comment by evaherrada** [comment]
Will do

**Comment by evaherrada** [comment]
@siddacious The cc3000 has been discontinued so I can't test on that hardware. Do you think I'd be able to test it with the metro airlift?

**Comment by ladyada** [comment]
close all issues and archive this repo

**Comment by evaherrada** [comment]
@ladyada will do
