### ISSUE TITLE
TCP/IP server crashes after a couple of requests. The timing seems to be random.

### ISSUE THREAD

**Issue by vheun** [adafruit/Adafruit_CC3000_Library#51]
It feels like it is related to: 
- When the requesting side stops the connection and opens one (or many) new ones to fast.
- Maybe to many packages send in the same time?
- Maybe some buffers that are overrun in the Adafruit Library? 
  # Are more people having this issue?

Could it be possible to have a function that tells if all packages are received, send successfully or unable to send due a closed connection? This function can help me to wait until the message is send instead of just blindly delay by a magical amount.
Is something like that supported by the cc3000?

**Comment by vheun** [comment]
3 people asked my be now what the ominous platform is that I moved on to: We use the arduino Yun and build an open source platform on top of it that you can find here: openhybrid.org

**Comment by vk3who** [comment]
I am running a cc3000 WiFi Shield Uno8Mega compatible on a mega2560 and Uno and find that it locks up after a while and on a hot day it doesn’t initialize at all. The interesting thing is when I spray the 74HC4050D with freezer spray the board comes back to life until the chip reaches room temperature. I have checked the 74HC4050D with the oscilloscope and found no changes in the timing or voltage levels that I can see from cold to hot. I will try to replace the chip and see if that makes any difference. All that I can think of is that the time might be right on the edge and a bit of heat makes it fall over.

**Comment by vk3who** [comment]
Follow up on the times, using a better oscilloscope the difference between the freeze spray and the room temperature.
Room temperature(30C)
Propagation delay through 4050D is rise =47nS, fall=58nS
At Freeze spray temperature (-40C)  rise= 38ns, fall =46ns  
According to the datasheet for ST semi-conductors M74HC4050 the propagation delay  shouldn’t be more than 15ns @ 4.5 Volts. I try a new chip shortly to see if there is any difference.
