### ISSUE TITLE
UDP Server example

### ISSUE THREAD

**Issue by briggsm** [adafruit/Adafruit_CC3000_Library#82]
It looks like (from your Adafruit CC3000 Wifi Shield & Breakout Board product pages) that the  CC3000 supports: "TCP and UDP in both client and server mode".  And your library currently supports: "UDP/TCP client & TCP server connections".

Is the UDP Server side of things a work in progress?  Or is it something too complicated to implement?

I think I need a UDP server to be setup for what I'm trying to accomplish (and I'd think many other users would like to do as well) - I'd like to rapidly send "Color" packets to control your NeoPixel strips.  I need at a MINIMUM 20 packets (colors) / second, though 30 or more would be best (no flickering).  Using the TCP server method I got about 2 frames / sec, and with some hacking, got it up to about 5 frames / sec.  (I may be doing something wrong, but I've even analyzed the TCP stream with Wireshark, and it appears the CC3000 side of things has about a 20ms delay before sending most or all of it's packets - which adds up to a lot of time pretty fast).

I have Javascript which AJAX calls a PHP script on a mouse move/drag event on a color swatch.  The called PHP script gets the color and sends it out as a UDP packet to where ever you tell it.

I understand the UDP Server is not currently supported in the library, but if you could point me in the right direction (if possible) I would greatly appreciate it!  Any solution to receiving ~20-30 packets / second of color (3 data bytes) packets would be great!

**Comment by Asherfri** [comment]
Guys, I am using the UDP server library. But for some reason after 5-10 minutes of operation, it stops responding. Even if I stay on idle for the whole period of time. Any ideas?
